// <auto-generated />
namespace CRM__EntityFramework_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _010420222 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_010420222));
        
        string IMigrationMetadata.Id
        {
            get { return "202204011632491_01.04.20222"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
